### ISSUE TITLE
Predix East(SELECT) - handshake issue

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-sdk#13] opened 2017-01-06 21:04 UTC
could not establish the handshake with the gateway from on-premise to Predix East environment

**Comment by chiacchang** [comment] 2017-01-06 22:19
Verifying.

**Comment by chiacchang** [comment] 2017-01-06 22:57
Issue identified.. it's being caused by the ip filtering and a set of malformed ip addresses on the GE Predix East Env. Will roll out a patch soon in next release.

**Comment by chiacchang** [comment] 2017-01-07 02:23
The issue has been fixed in v1.75 release. @palokam

**Closed** 2017-01-07 02:24 UTC
Labels: bug
